#!/usr/bin/env python
import rospy
from std_msgs.msg import String


class listener(object):
    def __init__(self):
        self.sub = rospy.Subscriber("subject_topic", String, self.callback)

    def callback(self, message):
        rospy.loginfo( "ROS_1 listener listening to %s", message.data)

def main():
    rospy.init_node('ros1_listener')
    listener()
    rospy.spin()

if __name__ == '__main__':
    main()